minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@spartan-ng/*'
  - '@ng-icons/*'
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: false
