minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@angular/*'
  - '@angular-devkit/*'
  - '@schematics/angular*'
  - '@ng-icons/*'
  - '@spartan-ng/*'
  - 'postcss@8.5.27'

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: false
