minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@spartan-ng/*'
  - postcss@8.5.29

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: false
